services:
  db:
    image: postgres:15-alpine
    container_name: comisiones-db-local
    restart: always
    environment:
      POSTGRES_USER: user_local
      POSTGRES_PASSWORD: password_local
      POSTGRES_DB: comisiones_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
